"""update models

Revision ID: 3f7692b07d46
Revises: 6a38177398c2
Create Date: 2022-05-09 07:30:57.956538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7692b07d46'
down_revision = '6a38177398c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('product', 'production_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('production_time', sa.DATETIME(), nullable=True))
    op.drop_column('product', 'amount')
    # ### end Alembic commands ###
