"""don't index brand and model

Revision ID: 60bc04d1f0ee
Revises: 3f7692b07d46
Create Date: 2022-05-09 07:39:50.272868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bc04d1f0ee'
down_revision = '3f7692b07d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_brand', table_name='product')
    op.drop_index('ix_product_model', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_model', 'product', ['model'], unique=False)
    op.create_index('ix_product_brand', 'product', ['brand'], unique=False)
    # ### end Alembic commands ###
