"""add admin id in the product

Revision ID: 6a38177398c2
Revises: 6cb360748a37
Create Date: 2022-03-22 22:47:37.855343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a38177398c2'
down_revision = '6cb360748a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'admin_id')
    # ### end Alembic commands ###
